sonar.projectKey=BrendaRaquel4_buku
sonar.organization=brendaraquel4

sonar.sources=buku.py,bukuserver,bukuserver-runner
sonar.tests=tests
sonar.exclusions=tests/cassettes/**,tests/vcr_cassettes/**

sonar.python.version=3.10,3.11,3.12,3.13
sonar.python.coverage.reportPaths=coverage.xml
